{"name": "test_login_without_password", "status": "failed", "statusDetails": {"message": "AssertionError: Status code 400 was expected and code 504 was returned.\nassert 504 == 400\n +  where 504 = <Response [504]>.status_code", "trace": "self = <test.test_CourierLogin.TestWithoutData object at 0x000002004A3BFB10>, base_url = 'http://qa-scooter.praktikum-services.ru/api/v1/'\n\n    def test_login_without_password(self, base_url):\n      # logger.info(\"Testing order acceptance without order ID\")\n       json_data = {\n       \"login\": \"Vasiliy\"\n       }\n       response = requests.post(base_url + \"courier/login\", data=json_data)\n      # logger.debug(f\"Status code {response.status_code} was returned and message{response.json()}\")\n>      assert response.status_code == 400, f\"Status code 400 was expected and code {response.status_code} was returned.\"\nE      AssertionError: Status code 400 was expected and code 504 was returned.\nE      assert 504 == 400\nE       +  where 504 = <Response [504]>.status_code\n\ntest\\test_CourierLogin.py:38: AssertionError"}, "start": 1693322000229, "stop": 1693322060385, "uuid": "43b5ad88-a225-4b91-b85a-adfa17d703d8", "historyId": "46f10ba66826f7134aefca13aa8bfe9a", "testCaseId": "46f10ba66826f7134aefca13aa8bfe9a", "fullName": "test.test_CourierLogin.TestWithoutData#test_login_without_password", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_CourierLogin"}, {"name": "subSuite", "value": "TestWithoutData"}, {"name": "host", "value": "DESKTOP-36NVPK8"}, {"name": "thread", "value": "260-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_CourierLogin"}]}