{"name": "test_deletion_without_id", "status": "failed", "statusDetails": {"message": "AssertionError: Status code 400 was expected and code 404 was returned.\nassert 404 == 400\n +  where 404 = <Response [404]>.status_code", "trace": "self = <test.test_CourierDelete.TestDeleteCourier object at 0x000001B2E7178CD0>, base_url = 'http://qa-scooter.praktikum-services.ru/api/v1/'\n\n    def test_deletion_without_id(self, base_url):\n        response = requests.delete(base_url + \"courier\")\n>       assert response.status_code == 400, f\"Status code 400 was expected and code {response.status_code} was returned.\"\nE       AssertionError: Status code 400 was expected and code 404 was returned.\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntest\\test_CourierDelete.py:17: AssertionError"}, "start": 1692259561768, "stop": 1692259561911, "uuid": "6fcca820-06f2-4db4-8923-2a9baacd4aaa", "historyId": "25d7ffea571398379f3339ab13d304ac", "testCaseId": "25d7ffea571398379f3339ab13d304ac", "fullName": "test.test_CourierDelete.TestDeleteCourier#test_deletion_without_id", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_CourierDelete"}, {"name": "subSuite", "value": "TestDeleteCourier"}, {"name": "host", "value": "DESKTOP-36NVPK8"}, {"name": "thread", "value": "1756-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_CourierDelete"}]}